project:
  type: website
  output-dir: docs

website:
  title: "LN OST"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - courses.qmd
      - course_content.qmd
      - about_us.qmd
      - contact.qmd

  page-footer:
    left: "This page is built with ‚ù§Ô∏èüß†, some ü™Ñ and [Quarto](https://quarto.org/)."
    right:
    - text: "Contact"
      href: contact.qmd

format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      # dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    # mainfont: "Atkinson Hyperlegible"
    # include-in-header: "style/fontawesome.html"

editor: visual
